### ISSUE TITLE
Pod for DBIx::Class::Events 0.9.1

### ISSUE THREAD

**Issue by jimeUWOshkosh** [GrantStreetGroup/p5-DBIx-Class-Events#2]
Halo
In DBIx::Class::Events#Tracked-Table section you need to add 'previousid' to the Artist.pm

Also if you run the sample program twice in a row, you get
   DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that 
   returns multiple rows is DEPRECATED for ->find and ->single at dce.pl line 40

I've created a repository of my work
https://github.com/jimeUWOshkosh/DCE
If you want to create a 'examples' directory like DBIx::Class, it would be a good starting point.
My README shows how I created it.

Thanks for your time
James Edwards
Have a great day!!!

**Comment by afresh1** [comment]
Many thanks!  I will take a look when I get back to work on the 20th.  If you want to submit a PR with your suggested changes someone who is there will likely be able to merge them.

**Comment by jimeUWOshkosh** [comment]
Created 2 PRs:
1) for POD changes 
2) An 'examples' directory like DBIx::Class'

Thanks for your time. Have a great day!!!
